version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management # Docker image for RabbitMQ with management plugin
    ports:
      - "5672:5672" # RabbitMQ default port
    networks:
      - my_network

  mongodb:
    image: mongo # Official MongoDB image
    ports:
      - "27017:27017" # MongoDB default port
    networks:
      - my_network

  sender:
    build: ./wao10Sender # Path to the directory containing your sender Node.js application Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq # Set the hostname of RabbitMQ
    networks:
      - my_network

  receiver:
    build: ./wao10Reciver # Path to the directory containing your receiver Node.js application Dockerfile
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_HOST=rabbitmq # Set the hostname of RabbitMQ
      - MONGODB_HOST=mongodb # Set the hostname of MongoDB
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
